# Generated by Django 5.1.7 on 2025-04-01 12:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Landlord',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('mobile_number', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_subscription', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Landlord',
                'verbose_name_plural': 'Landlords',
                'db_table': 'landlord',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('property_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='myapp.landlord')),
            ],
            options={
                'db_table': 'property',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10)),
                ('is_occupied', models.BooleanField(default=False)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='myapp.property')),
            ],
            options={
                'db_table': 'room',
                'ordering': ['room_number'],
            },
        ),
        migrations.CreateModel(
            name='Electricity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_date', models.DateField(default=django.utils.timezone.now)),
                ('last_reading', models.FloatField()),
                ('current_reading', models.FloatField()),
                ('consumption', models.FloatField(default=None)),
                ('rate', models.FloatField(default=10.1)),
                ('total_amount', models.FloatField(default=None)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electrcitys', to='myapp.room')),
            ],
            options={
                'db_table': 'electrcity',
                'ordering': ['reading_date'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('mobile_number', models.CharField(max_length=15)),
                ('total_person', models.IntegerField(default=1)),
                ('aadhar_photo', models.TextField()),
                ('other_images', models.TextField()),
                ('move_in_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenant', to='myapp.room')),
            ],
            options={
                'db_table': 'tenant',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_due', models.DecimalField(decimal_places=2, default=None, max_digits=10)),
                ('is_paid', models.BooleanField(default=True)),
                ('payment_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.room')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='myapp.tenant')),
            ],
            options={
                'db_table': 'payment',
                'ordering': ['year', 'month'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'room', 'month', 'year'), name='unique_payment_per_month')],
            },
        ),
    ]
